#!/usr/bin/env python3

import openai, sys, signal, markdown, subprocess
from colorama import Fore, Style, init
from os import environ

# OpenAI Settings
gpt_model = 'gpt-3.5-turbo'         # Your default configured AI assistant
num_of_samples=1                    # If you want longer paragraph response increase this value (experiment)
temperature=1.0                     # Controls creativity of prepared answer. Higher temp results in more unpredictable answers
max_tokens=50                       # Number of tokens (words or subwords) model will generate for response. Truncates response upon reach
openai.api_key = environ['api_key'] # Your exported OpenAI API secret key

# Needed for some linux terminals when using colorama
init()

# Construct ChatGTP answer
def prepare_answer(answer=None):
    messages.append({"role": "user", "content": message})
    chat_completion = openai.ChatCompletion.create(
        model=f"{gpt_model}",
        n=num_of_samples,
        temperature=temperature,
        max_tokens=max_tokens,
        messages=messages)
    answer = chat_completion.choices[0].message.content
    markdown_check_response(answer)

# Markdown check and response
def markdown_check_response(answer):
    if markdown.markdown(answer) != answer:
        subprocess.run(
            ["mdcat"], input=f"{Fore.YELLOW}ChatGPT:{Fore.RESET} {answer}".encode())
    else:
        print(f"{Fore.GREEN}ChatGPT: {Style.RESET_ALL}{answer}")
        messages.append({"role": "assistant", "content": answer})

# Handle CTRL_C grafecully
def signal_handler(sig, frame):
    client_exit(sig)
    sys.exit(0)

# Client exit
def client_exit(sig=None):
    if sig:
        print(f'\nExiting Client ...')
    else:
        print('Exiting Client...')

# Define init client variables
you = subprocess.check_output(['whoami']).decode('utf-8').strip().capitalize()
messages = [{"role": "system", "content": "ChatBot Ready"}, ]

# Set signal handler
signal.signal(signal.SIGINT, signal_handler)

# Check if you passed an argument. Starting non-conversation mode
if len(sys.argv) > 1:
    message = ' '.join(sys.argv[1:])
    prepare_answer()
else:
    # You are going into conversation mode
    message = True
    while message:
        message = input(Fore.CYAN + f"{you}: " + Style.RESET_ALL)
        if message == '':
            client_exit()
        elif message:
            prepare_answer()